name: CI/CD Pipeline to MyServer

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装 sshpass 工具
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # 部署到服务器
      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            # 添加 safe.directory 配置
            git config --global --add safe.directory /web/KaZ &&
            cd /web/KaZ &&
            git fetch origin main &&
            git reset --hard origin/main &&
            corepack enable &&
            corepack prepare yarn@4.7.0 --activate
          '

      # 开启服务
      - name: Start Service
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            # 检查是否存在 dev_web 进程
            if pm2 list | grep -q "dev_web"; then
              echo "dev_web 进程存在，正在删除..."
              pm2 delete dev_web
            else
              echo "dev_web 进程不存在，跳过删除。"
            fi
            # 安装依赖
            yarn &&
            # 使用 PM2 启动项目
            pm2 start yarn --name "dev_web" -- dev:web
          '
        if: always()
